# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_score_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='duration',
        ),
    ]
