# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_score_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='Score_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
